version: "3.4"

services:
  web:
    image: emvee/ucn-frontend:latest
    restart: always
    depends_on:
      - api
    ports:
      - "8080:80"

  api:
    image: emvee/ucn-backend:latest
    restart: always
    ports:
      - "3000:80"
      - "3001:433"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    restart: always
    ports:
      - "1400:1433"
    volumes:
      - /var/mssql/data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
