version: "3.4"

services:
  web:
    image: emvee/ucn-frontend:latest
    restart: always
    volumes:
      - /var/www/foodpanda.dk/html/:/app/dist/build/
    depends_on:
      - api
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_URL=${API_URL}
      - FRONTEND_DEV_PORT=${FRONTEND_DEV_PORT}
      - FRONTEND_DEV_HOST=${FRONTEND_DEV_HOST}


  api:
    image: emvee/ucn-backend:latest
    restart: always
    ports:
      - "3000:80"
      - "3001:433"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "1400:1433"
    volumes:
      - /var/mssql/data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "Y"
