
name: Docker Image Backend
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image backend
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ucn-backend ./backend/UCN-Semester-3-project/
    - name: Push the Docker image
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} && docker push ${{ secrets.DOCKERHUB_USERNAME }}/ucn-backend:latest

    - name: webhook backend
      uses: wei/curl@v1
      with:
        args: -X POST {{ API_WEBHOOK }}