
name: Docker Image Frontend
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image frontend
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ucn-frontend ./frontend/
    - name: Push the Docker image
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} && docker push ${{ secrets.DOCKERHUB_USERNAME }}/ucn-frontend:latest
  
    - name: webhook frontend
      uses: wei/curl@v1
      with:
        args: -X POST ${{ secrets.FRONTEND_WEBHOOK }}

