
name: Docker Image CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image backend
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ucn-backend ./backend/UCN-Semester-3-project/
    - name: Push the Docker image
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} && docker push ${{ secrets.DOCKERHUB_USERNAME }}/ucn-backend:latest

    - name: webhook backend
      uses: wei/curl@v1
      with:
        args: -X POST http://157.230.22.150/portainer/api/webhooks/b0449aa2-10a2-4187-acf0-a87247029bbf