
name: Docker Image CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image frontend
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ucn-frontend ./frontend/
    - name: Push the Docker image
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} && docker push ${{ secrets.DOCKERHUB_USERNAME }}/ucn-frontend:latest
  
    - uses: actions/checkout@v2
    - name: Build the Docker image backend
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/reciperestservice ./backend/UCN-Semester-3-project/RecipeRestService/
    - name: Push the Docker image
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} && docker push ${{ secrets.DOCKERHUB_USERNAME }}/reciperestservice:latest
